//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZingitWizard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZingitWizard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Coffee Wizard.
        /// </summary>
        public static string ApplicationMainWindow_Button_RunWizard {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Button_RunWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cancelled.
        /// </summary>
        public static string ApplicationMainWindow_OrderCancelled {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_OrderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cup of coffee costs {0}, thank you..
        /// </summary>
        public static string ApplicationMainWindow_OrderComplete_Formatted {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_OrderComplete_Formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JJ &amp; k-dawg&apos;s Coffee.
        /// </summary>
        public static string ApplicationMainWindow_Title {
            get {
                return ResourceManager.GetString("ApplicationMainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Blend.
        /// </summary>
        public static string BeanType_Breakfast {
            get {
                return ResourceManager.GetString("BeanType_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Roast.
        /// </summary>
        public static string BeanType_DarkRoast {
            get {
                return ResourceManager.GetString("BeanType_DarkRoast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Blend.
        /// </summary>
        public static string BeanType_House {
            get {
                return ResourceManager.GetString("BeanType_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Roast.
        /// </summary>
        public static string BeanType_LightRoast {
            get {
                return ResourceManager.GetString("BeanType_LightRoast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic.
        /// </summary>
        public static string BeanType_Organic {
            get {
                return ResourceManager.GetString("BeanType_Organic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavorings.
        /// </summary>
        public static string CoffeeExtrasPageView_Header_Flavorings {
            get {
                return ResourceManager.GetString("CoffeeExtrasPageView_Header_Flavorings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string CoffeeExtrasPageView_Header_Temperature {
            get {
                return ResourceManager.GetString("CoffeeExtrasPageView_Header_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bean Type.
        /// </summary>
        public static string CoffeeSummaryPageView_Header_BeanType {
            get {
                return ResourceManager.GetString("CoffeeSummaryPageView_Header_BeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Drink Size.
        /// </summary>
        public static string CoffeeSummaryPageView_Header_DrinkSize {
            get {
                return ResourceManager.GetString("CoffeeSummaryPageView_Header_DrinkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Flavorings.
        /// </summary>
        public static string CoffeeSummaryPageView_Header_Flavorings {
            get {
                return ResourceManager.GetString("CoffeeSummaryPageView_Header_Flavorings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Temperature.
        /// </summary>
        public static string CoffeeSummaryPageView_Header_Temperature {
            get {
                return ResourceManager.GetString("CoffeeSummaryPageView_Header_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string CoffeeSummaryPageViewModel_Label_NoFlavoringsSelected {
            get {
                return ResourceManager.GetString("CoffeeSummaryPageViewModel_Label_NoFlavoringsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bean Type.
        /// </summary>
        public static string CoffeeTypeSizePageView_Header_BeanType {
            get {
                return ResourceManager.GetString("CoffeeTypeSizePageView_Header_BeanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink Size.
        /// </summary>
        public static string CoffeeTypeSizePageView_Header_DrinkSize {
            get {
                return ResourceManager.GetString("CoffeeTypeSizePageView_Header_DrinkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cup of Coffee.
        /// </summary>
        public static string CoffeeWizardDialog_Title {
            get {
                return ResourceManager.GetString("CoffeeWizardDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CoffeeWizardView_Button_Cancel {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string CoffeeWizardView_Button_Finish {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string CoffeeWizardView_Button_MoveNext {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string CoffeeWizardView_Button_MovePrevious {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Button_MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string CoffeeWizardView_Header_Steps {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Header_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CoffeeWizardView_Label_Price {
            get {
                return ResourceManager.GetString("CoffeeWizardView_Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string DrinkSize_Large {
            get {
                return ResourceManager.GetString("DrinkSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DrinkSize_Medium {
            get {
                return ResourceManager.GetString("DrinkSize_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string DrinkSize_Small {
            get {
                return ResourceManager.GetString("DrinkSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caramel.
        /// </summary>
        public static string Flavoring_Caramel {
            get {
                return ResourceManager.GetString("Flavoring_Caramel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gingerbread.
        /// </summary>
        public static string Flavoring_Gingerbread {
            get {
                return ResourceManager.GetString("Flavoring_Gingerbread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazelnut.
        /// </summary>
        public static string Flavoring_Hazelnut {
            get {
                return ResourceManager.GetString("Flavoring_Hazelnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish Cream.
        /// </summary>
        public static string Flavoring_IrishCream {
            get {
                return ResourceManager.GetString("Flavoring_IrishCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Flavoring_None {
            get {
                return ResourceManager.GetString("Flavoring_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin.
        /// </summary>
        public static string Flavoring_Pumpkin {
            get {
                return ResourceManager.GetString("Flavoring_Pumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla.
        /// </summary>
        public static string Flavoring_Vanilla {
            get {
                return ResourceManager.GetString("Flavoring_Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Files.
        /// </summary>
        public static string PageDisplayName_CopyFiles {
            get {
                return ResourceManager.GetString("PageDisplayName_CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string PageDisplayName_Extras {
            get {
                return ResourceManager.GetString("PageDisplayName_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PageDisplayName_Summary {
            get {
                return ResourceManager.GetString("PageDisplayName_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink Size / Bean Type.
        /// </summary>
        public static string PageDisplayName_TypeAndSize {
            get {
                return ResourceManager.GetString("PageDisplayName_TypeAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string PageDisplayName_Welcome {
            get {
                return ResourceManager.GetString("PageDisplayName_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Hot.
        /// </summary>
        public static string Temperature_ExtraHot {
            get {
                return ResourceManager.GetString("Temperature_ExtraHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Temperature_Normal {
            get {
                return ResourceManager.GetString("Temperature_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Ice.
        /// </summary>
        public static string Temperature_WithIce {
            get {
                return ResourceManager.GetString("Temperature_WithIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zingit Automation Install Wizard.
        /// </summary>
        public static string ZingitInstallation_Title {
            get {
                return ResourceManager.GetString("ZingitInstallation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Progress.
        /// </summary>
        public static string ZingitWizardView_Header_Steps {
            get {
                return ResourceManager.GetString("ZingitWizardView_Header_Steps", resourceCulture);
            }
        }
    }
}
